train:
	python3 train.py

table:
	python3 ../../scripts/show_table.py

test:
	python3 get_predictions.py ${MODEL}

mAP:
	python ../../scripts/eval/get_mAP.py

show:
	python3 ../../scripts/eval/visualize.py ${THRES}
